### ISSUE TITLE
Feature request: Add "desired temperature" to keg on creation

### ISSUE THREAD

**Issue by trestrantham** [collectiveidea/bender#3]
Desired temperature will be the desired keg (or pour) temperature. A min/max threshold could automatically be calculated to control the kegerator cutoff temperature ranges and could be configured in an admin configuration/settings page.

If more than one keg is active, the kegerator temperature would be the average of all desired temperatures.

We could also optionally/automatically subtract X degrees to compensate for the 'warm up' between pouring and drinking.

**Comment by asheren** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If you would still like this issue to be addressed, please re-open it by May 17, 2017. Thanks!
